alias tree='tree -A'
alias LS='ls'
alias rr='rm -r'
alias rrf='rm -rf'

alias s='svn'
alias sa='svn add'
alias sr='svn revert --depth=infinity'
alias sd='svn diff --diff-cmd=meld'
alias se='svn export'
alias si='svn info'
alias sdd='svn delete'
alias sup='svn update'
alias sst='svn st -qu'
alias sll='svn log -l'
alias sls='svn list'
alias ssw='svn switch'
alias sco='svn co'
alias sci='svn ci -m'
alias ssx='svn propset svn:executable on'
alias sdx='svn propdel svn:executable'

alias gdiff='git difftool -y -t meld'

alias a='sudo apt-get'
alias a-s='aptitude search'
alias a-i='sudo apt-get install'
alias a-r='sudo apt-get remove'
alias a-p='sudo apt-get purge'
alias a-a='sudo apt-get autoremove'
alias a-c='sudo apt-get autoclean'

alias e='gvim'
alias ep='gvim -p'
alias ea='gvim ~/.bash_aliases'
alias ez='gvim ~/.zsh_aliases'
alias ev='gvim ~/.vimrc'
alias es='gvim -S'
alias res='[ -e Session.vim ] && gvim -S Session.vim || print "No session to resume"'

alias xo='xdg-open'
alias mx='chmod +x'
alias cls='for i in `seq 30`; do echo -e "\n"; done'
alias gmeld='git difftool --tool=meld -y'
alias grp='grep -rIn'

alias q='quilt'
alias qa='quilt add'
alias qd='quilt diff'
alias qdd='quilt delete'
alias qf='quilt files'
alias qn='quilt new'
alias qp='quilt pop'
alias qph='quilt push'
alias qi='quilt import'
alias qr='quilt refresh'
alias qrm='quilt remove'
alias qs='quilt series'

alias b='bash -c'
